### ISSUE TITLE
the tool will not monitor if the chrome where whatsapp login is minimize

### ISSUE THREAD

**Issue by kepangada** [jasperan/whatsapp-osint#10]
Hello

when I try to minimize chrome which is used to enter WhatsApp, the tool will no longer monitor. This means that the chrome that is used to enter WhatsApp must be seen continuously and cannot be run in the background. I have a WhatsApp bot, is it possible to modify it to use it to monitor WhatsApp contacts online? https://github.com/kepangada/wo

**Comment by ChristianBdv** [comment]
Hello

It's the same for me, the script does not accommodate the connections and disconnections of the target...
I remain a little on my hunger, because it is very practical to follow the discreet profiles...

**Comment by jasperan** [comment]
Hello guys @ChristianBdv @kepangada , unfortunately it's not possible to receive this information in other ways. The reason for this is that there are no underlying API calls that reveal the online status of a user: it can only be obtained through visual HTML inspection

Therefore it can work for only the currently selected profile, and the window must be open. But you can have multiple WhatsApp sessions open in different tabs if you use different phone numbers (>1 phone number: >1 automated browser sessions)

**Comment by ChristianBdv** [comment]
Gracias por su respuesta, retomaré la configuración porque no tengo comentarios incluso con un solo número monitoreado. Te mantendré informado !!
Saludo

**Comment by jasperan** [comment]
@ChristianBdv que lenguaje tienes en el Sistema Operativo? Es importante que el lenguaje que utilices tenga "online" o "en línea", si está en otro idioma puede que haya problemas para detectar el código HTML en el que se extrae el online/offline status
