### ISSUE TITLE
User is not found when chat is no created before nor recent

### ISSUE THREAD

**Issue by Kino1994** [jasperan/whatsapp-osint#26]
joaquin@joaquin:~/git/whatsapp-osint$ python3 whatsappbeacon.py --username Laure --language "es"
In order to make this program to work, you will need to log-in once in WhatsApp. After that, your session will be saved until you revoke it.
Loading...
 Loaded
Trying to find: //span[contains(text(), 'Laure')]
Laure is not found. Returning...(Maybe your contact is in the archive. Check it)

Can be fixed if user is searched before.

I added this pull request to fix it: https://github.com/jasperan/whatsapp-osint/pull/25

**Comment by jasperan** [comment]
Fix merged, thank you!
