### ISSUE TITLE
Program finishes execution before Syncing is complete

### ISSUE THREAD

**Issue by BananaGeneral** [jasperan/whatsapp-osint#27]
So after linking a device using the QR code, the program tries to find the given username argument, but since the link just happened, there's no time for the browser to finish syncing all the conversations, and the program cannot find the contacts. 

```
 Loaded
Trying to find: Banana Kong
Banana Kong is not found. Returning...(Maybe your contact is in the archive. Check it)
```

![IMG_15F257F98E57-1](https://github.com/jasperan/whatsapp-osint/assets/20095478/3b154046-d111-4080-8fbe-8f5264ddbd2e)

If there was a way to keep the browser open to finish the syncing, the problem would be solved.

**Comment by jasperan** [comment]
@BananaGeneral how long does it take approximately? I've never seen this sync stuff before

**Comment by BananaGeneral** [comment]
I tested it on a new instance, and it took about one minute to complete. 
I imagine it varies depending on how many open conversations one has / the internet connection speed.

**Comment by jasperan** [comment]
If you re-run it with the saved session, do you run into issues? Just asking to check the priority of this issue because I have a lot of work right now and I want to know if it's severe or mid
