### ISSUE TITLE
script is stuck on loading...

### ISSUE THREAD

**Issue by Alexvbp** [jasperan/whatsapp-osint#32]
Hi,

I've tested this on windows and linux, whenever i launch the script it opens up chrome, i have scanned my QR it is stuck on "loading...".
On linux i am using python 3.10 and Chrome for testing v119.0.6045.105 with matching chromedriver.

**Comment by jasperan** [comment]
Hello @Alexvbp , I have just tested with your Chromedriver version: 
![image](https://github.com/jasperan/whatsapp-osint/assets/20752424/e6663dc7-9936-4ad8-9b46-bf87e3d354f8)

It seems to be working fine. Please, paste here what you see on the terminal. Do you arrive to my step on the picture?

**Comment by Alexvbp** [comment]
Hi @jasperan, hereby a screenshot of my output:
![Unsaved Image 1](https://github.com/jasperan/whatsapp-osint/assets/62056420/7ed5ceb7-4268-4a69-b6e0-a75daf2052f5)

**Comment by jasperan** [comment]
Hi @Alexvbp , the script is failing to find the following XPATH: //div[@data-testid="**wa-web-loading-screen**"]

Can you try to find the location of this HTML div when you create a new incognito session and login to whatsapp? It is present during loading, and for some reason your client is not finding it, so it's stuck on loading as it can't find the login screen.

You can test this with Chrome Developer tools for example, by inspecting the HTML

**Comment by Alexvbp** [comment]
when i search for wa-web-loading-screen in all files at sources i don't seem to find it either.

**Comment by jasperan** [comment]
Here: 
![NVJWMIp](https://github.com/jasperan/whatsapp-osint/assets/20752424/65e347ff-7c8f-4145-96d2-73cf4c3814ab)

**Comment by Alexvbp** [comment]
That's odd, when i first go to web.whatsapp.com (before the QR screen) i get this:
![chrome_E4oKgcUKNe](https://github.com/jasperan/whatsapp-osint/assets/62056420/6012873f-ab44-4855-ba69-169d51cbc2fb)

I get the QR screen, scan my code and this is the very first thing i see:
![chrome_gtvPaR3EUo](https://github.com/jasperan/whatsapp-osint/assets/62056420/b1d407bd-97b8-417b-a341-3d291c2e6978)

after this my chats appear. my whatsapp isn't set up in any special way, not in any beta, i am using two step verification though but i dont think this should interfere?

**Comment by Alexvbp** [comment]
Hiya, not the most elegant fix, but in case anyone has the same problem.


```
def whatsapp_load(driver) -> None:
	"""
	Wait for the WhatsApp Web loading screen to disappear based on the disappearance of the resume-logo element.

	Args:
	- driver: Selenium WebDriver instance.

	Returns:
	None
	"""
	try:
		# Wait for the resume-logo to disappear, indicating loading is complete
		WebDriverWait(driver, 30).until_not(
			EC.presence_of_element_located((By.CSS_SELECTOR, "path.resume-logo"))
		)
		print("Loading complete.")

	except TimeoutException:
		print("Loading took too much time!")

	# Additional checks or actions after loading can be placed here if needed

```

I also added a find contact function because whatsapp doesnt always show the username instantly, sometimes it shows the phone numbers at first, causing it to close prematurely. if the user isnt loaded in the gui, you have to scroll down for them to load.

```
def find_contact(driver, user, timeout=30):
	"""
	Wait for a specific contact to appear in WhatsApp Web.
	...
	"""
	end_time = time.time() + timeout
	while time.time() < end_time:
		try:
			span = f"span[title='{user}']"
			element = driver.find_element(By.CSS_SELECTOR, span)
			return element
		except NoSuchElementException:
			time.sleep(1)  # Wait for 1 second before trying again
	return None
```

i've also changed the remove_idle function since it couldnt find `@data-testid="smiley"`
all in all, not very elegant but it works for me now.

```
def remove_idle(driver):
    while True:
        time.sleep(10)
        try:
            # Updated selector to target the smiley button
            smiley_button = driver.find_element(By.CSS_SELECTOR, 'button[aria-label="Open emojis panel"]')
            smiley_button.click()
        except NoSuchElementException:
            print('Smiley button not found.')
```
