### ISSUE TITLE
Help explain GUI. 

### ISSUE THREAD

**Issue by deepsynthsec** [jasperan/whatsapp-osint#5]
Here there. Can you explain how to set up a GUI for this please

**Comment by jasperan** [comment]
Hey @deepsynthsec, can you specify what you mean? This program is designed to work with a GUI (your computer screen, for example). You just need to run the code with a browser driver like ChromeDriver installed and you shouldn't run into any issues

**Comment by deepsynthsec** [comment]
Yes I figured that out thank you. But it stilo has a trackback error after trying to run it. 

It executes fine until you press any key after you are in the chat. 

Basically says that the log file doesn't exist

**Comment by jasperan** [comment]
@deepsynthsec yes, someone else also mentioned this error in https://github.com/jasperan/whatsapp-osint/issues/6#event-7280769674

We're on it and fixing it, make sure to turn notifications for the other issue and we'll give updates there

**Comment by deepsynthsec** [comment]
Thank you so much. This project has massive potential. Is there anything I can do to help

**Comment by deepsynthsec** [comment]
now i am just getting the log error

   whatsapp-osint   git:(master) sudo python whatsappbeacon.py
Traceback (most recent call last):
  File "/home/prophecy/Documents/git/whatsapp-osint/whatsappbeacon.py", line 11, in <module>
    from utils.logs_manager import Logs

**Comment by jasperan** [comment]
@deepsynthsec mind pulling and trying again? Pull request #7 has been merged
