### ISSUE TITLE
help logs_manager

### ISSUE THREAD

**Issue by awelmisin** [jasperan/whatsapp-osint#6]
Traceback (most recent call last):
  File "C:\Users\dedem\OneDrive\Belgeler\GitHub\whatsapp-osint\whatsappbeacon.py", line 11, in <module>
    from utils.logs_manager import Logs
ModuleNotFoundError: No module named 'utils.logs_manager'

**Comment by jasperan** [comment]
@ch0coflake -> @awelmisin

**Comment by jasperan** [comment]
@awelmisin, when you execute whatsappbeacon.py, in which directory are you located? You should run from the repository's root directory to avoid the Python interpreter not finding the reference 'utils.logs_manager'

**Comment by deepsynthsec** [comment]
   whatsapp-osint   git:(master) sudo python whatsappbeacon.py
Traceback (most recent call last):
  File "/home/prophecy/Documents/git/whatsapp-osint/whatsappbeacon.py", line 11, in <module>
    from utils.logs_manager import Logs

**Comment by ch0coflake** [comment]
Hey @deepsynthsec , in fact there is an error which causes the python script not to run because there is a folder missing, which we are adding now to this repository. I would suggest you to redownload now or create in the root folder, whatsapp-osint create a folder called "logs". It should be working with it.

**Comment by deepsynthsec** [comment]
Oh cool. 

I was thinking maybe that it was a user issue. I thought that the logmanager.py has different permissions then the whatsappbeacon.py file.

**Comment by jasperan** [comment]
@awelmisin mind pulling and trying again? Pull request #7 has been merged

**Comment by deepsynthsec** [comment]
same problem after pull, i thought it maybe access permissions but i chmod 777 the whole file and still traceback

Traceback (most recent call last):
  File "/home/prophecy/Documents/git/whatsapp-osint/whatsappbeacon.py", line 11, in <module>
    from utils.logs_manager import Logs
ModuleNotFoundError: No module named 'utils.logs_manager'

**Comment by jasperan** [comment]
Hello, I've just tested the new version and it's working.

![image](https://user-images.githubusercontent.com/20752424/187964440-1d3ed2c9-fdd9-4e74-8682-03b019b02f75.png)

I believe your problem is that you're executing this code from an incorrect path. You need to be in the root directory and run whatsappbeacon.py from within the root directory. If you don't, utils.logs_manager can never be found.

Are you running this code from VSCode? If so, make sure you specify the execution environment to be in the root directory, not from another dir. I recommend you test using cmder or other Windows-compatible shell that gives you more control over which directory you're at 

@deepsynthsec

**Comment by deepsynthsec** [comment]
forgive me, im really a noob at this.

when you say root i have no idea what that means, do you mean root as "su" 
or root of the repo. Im sorry if im expecting a lesson in python :)

**Comment by jasperan** [comment]
No problem, I'm here to help @deepsynthsec. A root directory is the top level directory of the repository. So, for example, if you downloaded to /home/prophecy/Documents/git/whatsapp-osint, the root directory where you should run the file is from /home/prophecy/Documents/git/whatsapp-osint. 

You should not run the python script from any other directory. When you run from VSCode, the default directory depends and can be changed in settings I believe (here's a link for more info https://stackoverflow.com/questions/38623138/vscode-how-to-set-working-directory-for-debugging-a-python-program)

I always use a terminal to run Python programs so I never run into issues like these.

Note that in my previous example, I'm executing the Python script from /home/$USER/git/whatsapp-osint. That's the root dir of the repository after I downloaded it.

**Comment by deepsynthsec** [comment]
I have tried to emulate what you have said and i think im clearly doing something wrong that doesnt have to do with the program. i ran as you said and have gotten this result

![2022-09-01_18-50](https://user-images.githubusercontent.com/94907418/187969606-db9b2f51-22bb-432d-9e5e-fb0516b8ed5b.png)

**Comment by deepsynthsec** [comment]
When i deactivate conda i get a selenium web driver error
![2022-09-01_19-16](https://user-images.githubusercontent.com/94907418/187974046-8733c3d1-1c7e-438d-89fe-a37576915d55.png)

**Comment by deepsynthsec** [comment]
I installed selenium with python and i seem to have it working? 
![2022-09-01_19-19](https://user-images.githubusercontent.com/94907418/187974580-766b9cc5-c8fc-4d69-a5a2-775c0391df24.png)

**Comment by deepsynthsec** [comment]
Works perfectly... I thought i would add a write up just so others know how to fix it.

Reasons i think it didnt work:

- Chrome needs to be installed
- make sure selenium is installed from python correctly (update it)
- run it from the repo root directory
- listen to @jasperan 

Thank you so much for your help

**Comment by jasperan** [comment]
Haha thanks @deepsynthsec for the comments, see you around

#fixed
