### ISSUE TITLE
Selenium Error

### ISSUE THREAD

**Issue by Gona2119** [jasperan/whatsapp-osint#9]
Hi! I've got the following error: "`line 1, in <module> from selenium import webdriver ModuleNotFoundError: No module named 'selenium'` any solutions? Also I've already run the command pip install -r requirements.txt. Ty

**Comment by jasperan** [comment]
Check if your Python and pip environments are pointing to the same place, I feel like you have installed the requirements in an environment and trying to execute the code with another

**Comment by Gona2119** [comment]
How can I check it? In the image I've attached shows that they're in the same path (I think)
![image](https://user-images.githubusercontent.com/93960734/225493986-6464466b-be89-4525-9226-0e6125030d07.png)

**Comment by jasperan** [comment]
Can you show the output of this command?


`pip freeze`

It will tell you which libraries you have installed in your environment

**Comment by jasperan** [comment]
I find this error which will probably help you more than me: https://stackoverflow.com/questions/31147660/importerror-no-module-named-selenium

Let me know if it works

**Comment by Gona2119** [comment]
![image](https://user-images.githubusercontent.com/93960734/225511324-b032c6f2-8671-43ee-b116-0d7c18ff3502.png)
Here's the output, but it says selenium. Btw in the link that you sent they talk about changing the interpeter in VSC, but I'm running the entire script in CMD.

**Comment by jasperan** [comment]
Do you have chromedriver too? Looks like you have selenium installed, it's weird that it wouldn't find the reference in the module. You can try download conda and create a new clean environment and test again

**Comment by Gona2119** [comment]
Tryed with conda and still the same error after reinstalling all, including python, selenium, etc 
![image](https://user-images.githubusercontent.com/93960734/225726207-fe948080-77b5-4c5e-9631-7bbfea742512.png)

**Comment by jasperan** [comment]
Wait, you're executing with python3, not python

**Comment by Gona2119** [comment]
There it is! Worked after changing python3 to python. It's strange bc that says in the how to use instructions, but worked. Ty man

**Comment by jasperan** [comment]
Great! Yes, it's usually because when the change was made between Python 2 and 3, many people in their instructions (including me) made a differentiation between Python 2 and 3 to avoid people's confusions

But since we've been having Python 3 for a while, nobody is having this issue at the moment. It will possibly happen again on the change to Python 4 

(some Python history for you @Gona2119 )

**Comment by Gona2119** [comment]
Nice to know some Python history, and btw cool proyect. Do you are currently studying any carreer or do you have any degree?

**Comment by jasperan** [comment]
Yes, I did my major on Computer Engineering and I've been working on AI/ML for about 4 years. You can find everything I have done in my readme: https://github.com/jasperan including other projects, workshops, hands-on labs, YouTube podcasts, video replays, and some pictures of me 

@Gona2119

**Comment by Gona2119** [comment]
Despues de leer un rato ví que eras de España jajajs. Muy interesante tus estudios y eso, justamente también estoy estudiando  con 20 años Ingeniería en computación en Argentina pero recien en mi segundo año académico y arrancando programación orientada a objetos asi que soy muy nuevo en todo esto porque venia acostumbrado a la programacion iterativa en C y Processing pero nada de Java. Mucha suerte en todos tus proyectos y a seguir asi por más. Gracias por toda la ayuda :)

**Comment by jasperan** [comment]
Gracias @Gona2119 , suerte a ti en la carrera también!
